#!/bin/bash

# TODO: not sure about going down this road here.
# at the moment this is just a base ubuntu box
# with go and gdb

provider=$VAGRANT_DEFAULT_PROVIDER
# TODO: option to override
box=hashicorp/precise64
# TODO: option to override
mem=1024
# TODO: maybe some mapping of emacs major-mode to provisioner
# as long as it can be kept simple
type=go

if [ -e "Vagrantfile" ]
then
  exit
fi

if [ -z "$provider" ]
then
  if [ "$(uname -s)" == "Darwin" ]
  then
    provider="vmware_fusion"
  else
    provider="vmware_workstation"
  fi
fi

if [ -z "$(vagrant box list | grep $box)" ]
then
  vagrant box add $box --provider $provider
fi

cat > Vagrantfile <<EOF
Vagrant.configure("2") do |config|
  config.vm.hostname = "$(basename $PWD)"

  config.vm.box = "$box"
  config.vm.synced_folder ".", "$PWD"

  config.vm.provision "shell", path: "$(dirname $0)/$type/provision.sh"

  [:vmware_fusion, :vmware_workstation].each do |name|
    config.vm.provider name do |v,override|
      v.vmx["memsize"] = "$mem"
    end
  end
end
EOF
